# Generated by Django 3.1.7 on 2021-03-06 20:51

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('torre', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1)),
                ('apartamento', models.CharField(default='', max_length=2)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Moradores',
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('envelope', 'Envelope'), ('caixa', 'Caixa'), ('pacote', 'Pacote')], max_length=20)),
                ('status', models.CharField(choices=[('naoRecebido', 'Não Retirado'), ('recebido', 'Retirado')], max_length=30)),
                ('recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('retirada', models.CharField(choices=[('6', '6h'), ('12', '12h'), ('24', '24h'), ('48', '48h'), ('72', '72h')], default='24', max_length=3)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temCorrespondencia_encomendas', to=settings.AUTH_USER_MODEL)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temCorrespondencia_moradores', to='temCorrespondencia.morador')),
            ],
            options={
                'ordering': ('-recebimento',),
            },
        ),
    ]
