# Generated by Django 3.1.7 on 2021-03-05 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=60)),
                ('tipoEncomenda', models.CharField(choices=[('envelope', 'Envelope'), ('caixa', 'Caixa'), ('pacote', 'Pacote')], max_length=20)),
                ('status', models.CharField(choices=[('envelope', 'Envelope'), ('caixa', 'Caixa'), ('pacote', 'Pacote')], max_length=30)),
                ('horaRecebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('horaRetirada', models.DateTimeField(choices=[('6', '6h'), ('12', '12h'), ('24', '24h'), ('48', '48h'), ('72', '72h')], default='24', max_length=2)),
            ],
            options={
                'ordering': ('-horaRecebimento',),
            },
        ),
    ]
