# Generated by Django 3.1.7 on 2021-03-05 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morador', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('envelope', 'Envelope'), ('caixa', 'Caixa'), ('pacote', 'Pacote')], max_length=20)),
                ('status', models.CharField(choices=[('naoRecebido', 'Não Recebido'), ('recebido', 'Recebido')], max_length=30)),
                ('recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('retirada', models.CharField(choices=[('6', '6h'), ('12', '12h'), ('24', '24h'), ('48', '48h'), ('72', '72h')], default='24', max_length=3)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temCorrespondencia_encomendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recebimento',),
            },
        ),
    ]
