# Generated by Django 3.1.7 on 2021-03-08 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='recebimento',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 7, 3, 52, 880970, tzinfo=utc)),
        ),
    ]
