# Generated by Django 3.1.7 on 2021-03-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='apartamento',
            field=models.CharField(default='', max_length=3),
        ),
    ]
