# Generated by Django 3.1.7 on 2021-03-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ('-recebimento',)},
        ),
        migrations.RenameField(
            model_name='encomenda',
            old_name='destinatario',
            new_name='morador',
        ),
        migrations.RenameField(
            model_name='encomenda',
            old_name='horaRecebimento',
            new_name='recebimento',
        ),
        migrations.RenameField(
            model_name='encomenda',
            old_name='horaRetirada',
            new_name='retirada',
        ),
        migrations.RenameField(
            model_name='encomenda',
            old_name='tipoEncomenda',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('naoRecebido', 'Não Recebido'), ('recebido', 'Recebido')], max_length=30),
        ),
    ]
