# Generated by Django 3.1.7 on 2021-03-08 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0002_auto_20210308_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='recebimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
