# Generated by Django 3.1.7 on 2021-03-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0003_auto_20210308_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('naoRetiradoP', 'Não Retirado (P)'), ('naoRetiradoFP', 'Não Retirado (FP)'), ('retirado', 'Retirado')], default='naoRecebidoP', max_length=30),
        ),
    ]
