# Generated by Django 3.1.7 on 2021-03-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0003_auto_20210305_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='retirada',
            field=models.DateTimeField(choices=[('6', '6'), ('12', '12'), ('24', '24'), ('48', '48'), ('72', '72')], default='24', max_length=3),
        ),
    ]
