# Generated by Django 3.1.7 on 2021-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0004_auto_20210305_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='retirada',
            field=models.CharField(choices=[('6', '6h'), ('12', '12h'), ('24', '24h'), ('48', '48h'), ('72', '72h')], default='24', max_length=3),
        ),
    ]
