# Generated by Django 3.1.7 on 2021-03-09 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temCorrespondencia', '0004_auto_20210308_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='recebimento',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
